Numpy Array operations

In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing: ", arr[2:7])
print("With Step: ", arr[1:8:2])
print("Negative Indexing: ", arr[-3])
print("Negative Slicing: ", arr[:-3])

Basic Slicing:  [3 4 5 6 7]
With Step:  [2 4 6 8]
Negative Indexing:  8
Negative Slicing:  [1 2 3 4 5 6 7]


2D Array Indexing/Slicing

In [7]:
arr_2d = np.array([[1, 2, 3], # 0th row
                   [4, 5, 6], # 1st row
                   [7, 8, 9]]) # 2nd row
print("Specific Element: ", arr_2d[1, 2]) # arr_2d[row, col/element]
print("Entire row: ", arr_2d[1])
print("Entire row: ", arr_2d[:, 1])

Specific Element:  6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


Sorting

In [12]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2d array by column: \n", np.sort(arr_2d_unsorted, axis=0)) # axis=0 means column wise sorting (top to bottom)
print("Sorted 2d array by row: \n", np.sort(arr_2d_unsorted, axis=1)) # axis=1 means row wise sorting (left to right)

Sorted array:  [1 1 2 3 4 5 6 9]
Sorted 2d array by column: 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2d array by row: 
 [[1 3]
 [1 2]
 [2 3]]


Filter

In [14]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_no = numbers[numbers % 2 == 0]
print("Even number: ", even_no)

Even number:  [ 2  4  6  8 10]


Filter with mask

In [22]:
mask = numbers > 5
print(mask)
print("Numbers greater than 5: ", numbers[mask])

[False False False False False  True  True  True  True  True]
Numbers greater than 5:  [ 6  7  8  9 10]


Fancy Indexing vs np.where

In [ ]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5) # np.where finds where the condition is true.
print(where_result)
print("NP where: ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [26]:
condition_array = np.where(numbers > 5, numbers*2, numbers) # np.where(condition, execution (if), execution (else))

# the above can be written as: 
# if (numbers > 5):
    # numbers*2
# else:
#   numbers

print(condition_array)

# Another example
condition = np.where(numbers > 5, "true", "false")
print(condition)

[ 1  2  3  4  5 12 14 16 18 20]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


Adding and removing data

In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


Array compatibility

In [33]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes: ", a.shape == b.shape == c.shape)

Compatibility shapes:  True


In [38]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row)) # vstack adds row
print("Original: \n", original)
print("With New row: \n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With New column: \n", with_new_col)

Original: 
 [[1 2]
 [3 4]]
With New row: 
 [[1 2]
 [3 4]
 [5 6]]
With New column: 
 [[1 2 7]
 [3 4 8]]


In [39]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
