Learn about numpy with chai aur code


In [1]:
import numpy as np

creating array from list

In [17]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: \n", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: \n", arr_2d)

1D array: 
 [1 2 3 4 5]
2D array: 
 [[1 2 3]
 [4 5 6]]


List vs Numpy array

In [8]:
py_list = [1, 2, 3]
print("Python list multiplication: ", py_list*2)

np_arr = np.array([1, 2, 3]) # element wise mulitplication
print("Python array multiplication: ", np_arr*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_arr = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 List operation time:  0.06961369514465332

 Numpy operation time:  0.017927885055541992


In [12]:
arr = np.arange(10) # np.arange(start, stop, step)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Creating array from scratch

In [16]:
zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
