Learn about numpy with chai aur code


In [2]:
import numpy as np

creating array from list

In [17]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: \n", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: \n", arr_2d)

1D array: 
 [1 2 3 4 5]
2D array: 
 [[1 2 3]
 [4 5 6]]


List vs Numpy array

In [8]:
py_list = [1, 2, 3]
print("Python list multiplication: ", py_list*2)

np_arr = np.array([1, 2, 3]) # element wise mulitplication
print("Python array multiplication: ", np_arr*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_arr = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 List operation time:  0.06961369514465332

 Numpy operation time:  0.017927885055541992


In [12]:
arr = np.arange(10) # np.arange(start, stop, step)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Creating array from scratch

In [11]:
zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

ones = np.ones((2, 3))
print("Ones array: \n", ones)

full = np.full((2, 2), 7)
print("Full array: \n", full)

random = np.random.random((2, 3))
print("Random array: \n", random)

sequence = np.arange(0, 11, 2)
print("Sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.65989751 0.90170713 0.22536688]
 [0.54210098 0.61902325 0.18234167]]
Sequence array: 
 [ 0  2  4  6  8 10]


Vector, Matrices and Tensor

In [31]:
vector = np.array([1, 2, 3])
print("Vector: \n", vector)

matrices = np.array([[1, 2, 3],
                     [4, 5, 6]])
print("Matrices: \n", matrices)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrices: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties

In [33]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data type: ", arr.dtype)
print("\n")

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)
print("Shape: ", tensor.shape)
print("Dimension: ", tensor.ndim)
print("Size: ", tensor.size)
print("Data type: ", tensor.dtype)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Dimension:  2
Size:  6
Data type:  int64


Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape:  (2, 2, 2)
Dimension:  3
Size:  8
Data type:  int64


Array Reshaping

In [26]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped array: \n", reshaped)

flattened = reshaped.flatten()
print("Flattened array: \n", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Raveled array: \n", raveled)

# Transpose
transpose = reshaped.T
print("Transpose array: \n", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
